openapi: 3.0.3
info:
  title: 'Laravel API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/register:
    post:
      summary: 'Handle incoming registration request.'
      operationId: handleIncomingRegistrationRequest
      description: 'Dependency Injection: Laravel automatically injects the Action class.'
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: vmqeopfuudtdsufvyvddq
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 255 characters.'
                  example: kunde.eloisa@example.com
                password:
                  type: string
                  description: ''
                  example: consequatur
                role:
                  type: string
                  description: ''
                  example: customer
                  enum:
                    - creator
                    - customer
              required:
                - name
                - email
                - password
                - role
      security: []
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: qkunze@example.com
                password:
                  type: string
                  description: ''
                  example: 'O[2UZ5ij-e/dl4m{o,'
              required:
                - email
                - password
      security: []
  /api/products:
    get:
      summary: 'List all products (Public).'
      operationId: listAllProductsPublic
      description: 'Supports filtering and sorting.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      title: 'My First Ebook'
                      description: 'Learn Laravel fast'
                      price_formatted: '10.00'
                      creator_id: 1
                      created_at: '2026-01-26T22:53:11+00:00'
                  links:
                    first: 'http://localhost/api/products?page=1'
                    last: 'http://localhost/api/products?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        page: null
                        active: false
                      -
                        url: 'http://localhost/api/products?page=1'
                        label: '1'
                        page: 1
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        page: null
                        active: false
                    path: 'http://localhost/api/products'
                    per_page: 10
                    to: 1
                    total: 1
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        title: 'My First Ebook'
                        description: 'Learn Laravel fast'
                        price_formatted: '10.00'
                        creator_id: 1
                        created_at: '2026-01-26T22:53:11+00:00'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: 'My First Ebook'
                        description:
                          type: string
                          example: 'Learn Laravel fast'
                        price_formatted:
                          type: string
                          example: '10.00'
                        creator_id:
                          type: integer
                          example: 1
                        created_at:
                          type: string
                          example: '2026-01-26T22:53:11+00:00'
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost/api/products?page=1'
                      last:
                        type: string
                        example: 'http://localhost/api/products?page=1'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            page: null
                            active: false
                          -
                            url: 'http://localhost/api/products?page=1'
                            label: '1'
                            page: 1
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            page: null
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            page:
                              type: string
                              example: null
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost/api/products'
                      per_page:
                        type: integer
                        example: 10
                      to:
                        type: integer
                        example: 1
                      total:
                        type: integer
                        example: 1
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiProducts
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: vmqeopfuudtdsufvyvddq
                description:
                  type: string
                  description: ''
                  example: 'Dolores dolorum amet iste laborum eius est dolor.'
                price:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 13
                file:
                  type: string
                  format: binary
                  description: 'Must be a file. Must not be greater than 51200 kilobytes.'
              required:
                - title
                - description
                - price
                - file
      security: []
  /api/download-file:
    get:
      summary: 'Endpoint: The Signed URL points here.'
      operationId: endpointTheSignedURLPointsHere
      description: 'This actually delivers the file content.'
      parameters: []
      responses:
        403:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Invalid signature.'
                properties:
                  message:
                    type: string
                    example: 'Invalid signature.'
      tags:
        - Endpoints
      security: []
  '/api/products/{id}/purchase':
    post:
      summary: ''
      operationId: postApiProductsIdPurchase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/products/{id}/download':
    get:
      summary: "Endpoint: GET /api/products/{id}/download\nReturns: JSON with the temporary download link."
      operationId: endpointGETapiproductsiddownloadReturnsJSONWithTheTemporaryDownloadLink
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 1
        required: true
        schema:
          type: integer
